# Generated by Django 6.0 on 2025-12-18 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0003_alter_courier_user_alter_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=1, upload_to='category_photos'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=25, unique=True)),
                ('subcategory_image', models.ImageField(upload_to='subcategory_photos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glovo_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glovo_app.subcategory'),
            preserve_default=False,
        ),
    ]
